version: '3.8'

services:
  api:
    build: .
    ports:
      - '8000:8000'
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - TEMPERATURE=${TEMPERATURE}
      - MAX_TOKENS=${MAX_TOKENS}
      - TIMEOUT=${TIMEOUT}
      - MAX_RETRIES=${MAX_RETRIES}
    env_file:
      - .env
    volumes:
      - ./model:/app/model
